monitor=,preferred,auto,1

exec-once = sleep 2; waybar &
exec-once = nm-applet &
exec-once = obsidian
exec-once = ibus start --type=wayland &
exec-once = polkit-kde-agent
exec-once = swww-daemon
exec-once = swww img /home/rexdy/.config/wp.png
exec-once = dunst
exec-once = swayidle timeout 60 'exec swaylock' timeout 75 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' &

$terminal = terminator
$menu = wofi --show drun

env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_STYLE_OVERRIDE,kvantum
env = GTK_THEME,Adwaita-dark

input {
  kb_layout = us
  kb_variant =
  kb_model =
  kb_options =
  kb_rules =
  follow_mouse = 1

  touchpad {
    natural_scroll = yes
  }

  sensitivity = 0
}

general {
  gaps_in = 5
  gaps_out = 5
  border_size = 1
  col.active_border = rgba(ffffff55) rgba(00ff00aa) 45deg
  col.inactive_border = rgba(101010aa)
  layout = dwindle
  allow_tearing = false
}

decoration {
  rounding = 0

  blur {
    enabled = false
    size = 3
    passes = 1
  }
}

animations {
  enabled = yes
  bezier = myBezier, 0.05, 0.9, 0.1, 1.05
  animation = windows, 1, 5, myBezier
  animation = windowsOut, 1, 5, default, popin 90%
  animation = border, 1, 5, default
  animation = borderangle, 1, 5, default
  animation = fade, 1, 5, default
  animation = workspaces, 1, 2, default
}

dwindle {
  pseudotile = yes
  preserve_split = yes
}

gestures {
  workspace_swipe = off
}

misc {
  force_default_wallpaper = -1
  disable_hyprland_logo = true
}

binde = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
binde = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind = , XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle
binde = , XF86MonBrightnessUp, exec, brightnessctl set +10%
binde = , XF86MonBrightnessDown, exec, brightnessctl set 10%-

$mainMod = SUPER
bind = $mainMod, return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, F, fullscreen,
bind = $mainMod, M, exit,
bind = $mainMod, D, exec, $menu
bind = $mainMod, E, togglefloating,
bind = $mainMod, W, pseudo,
bind = $mainMod, C, togglesplit,
bind = $mainMod SHIFT, I, exec, swaylock -f -c 282a36
bind = $mainMod SHIFT, P, exec, systemctl poweroff
bind = $mainMod SHIFT, O, exec, systemctl reboot
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d
